name: Build C2EO

on: push

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { name: "Ubuntu", os: ubuntu-latest, cc: "gcc", cxx: "g++", archiver: "7z a", generators: "Ninja" }

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: c2eo
 
      - name: Move c2eo dir
        run: mv c2eo ~

      - name: Check tools version
        run: |
          gcc --version
          g++ --version
          git --version
          python3 --version
          mvn --version
          cmake --version
          sudo apt install ninja-build
          ninja --version

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: llvm-clang.tar.gz
          key: ${{ runner.os }}-llvm-clang

      - name: Unpack LLVM
        run: |
          sudo chmod ugo+rwx llvm-clang.tar.gz
          tar -xvf llvm-clang.tar.gz -C ~ > /dev/null
      
      - name: Build and test c2eo
        run: |
          cd ~/c2eo/project/build
          cmake ..
          make
          cd ../tests/scripts
          python3 -m unittest global_tests.GlobalIntegerTestCase.test_long_long_min
