name: Build C2EO

on: push

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { name: "Ubuntu", os: ubuntu-latest, cc: "gcc", cxx: "g++", archiver: "7z a", generators: "Ninja" }

    steps:
      - name: Tools versoins
        run: |
          gcc --version
          g++ --version
          git --version
          python3 --version
          mvn --version
          cmake --version
          sudo apt install ninja-build
          ninja --version
          echo ____________________________________
          pwd
          cd ~
          pwd
          ls


