name: Build C2EO

on:
  pull_request:
    branches:
      - master

  schedule:
    - cron:  '0 23 * * *'

jobs:

  cpp-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install cpplint
        run: sudo pip install cpplint

      - name: Cpp-lint
        run: cpplint --filter=-runtime/references,-runtime/string,-build/c++11 project/src/transpiler/** 

  clang-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Clang-format
        uses: jidicula/clang-format-action@v4.6.2
        with:
          clang-format-version: '13'
          check-path: 'project/src/transpiler'
          fallback-style: 'Google'

  clang-tidy:
    needs:
      - cpp-lint
      - clang-format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: llvm-clang.tar.gz
          key: ${{ runner.os }}-llvm-clang

      - name: Unpack LLVM
        run: |
          sudo chmod ugo+rwx llvm-clang.tar.gz
          tar -xvf llvm-clang.tar.gz -C ~ > /dev/null
          mv ~/llvm-clang .
      
      - name: Install clang-tidy
        run: sudo apt install clang-tidy
      
      - name: Clang-tidy
        run: |
          cd ./project/scripts
          python3 clang_tidy.py

  parsing:
    needs:
      - cpp-lint
      - clang-format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: llvm-clang.tar.gz
          key: ${{ runner.os }}-llvm-clang

      - name: Unpack LLVM
        run: |
          sudo chmod ugo+rwx llvm-clang.tar.gz
          tar -xvf llvm-clang.tar.gz -C ~ > /dev/null
          mv ~/llvm-clang .
          
      - name: Parsing
        run: |
          cd ./project/scripts
          python3 transpile.py ../tests/parsing -n

  test:
    needs:
      - cpp-lint
      - clang-format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: llvm-clang.tar.gz
          key: ${{ runner.os }}-llvm-clang

      - name: Unpack LLVM
        run: |
          sudo chmod ugo+rwx llvm-clang.tar.gz
          tar -xvf llvm-clang.tar.gz -C ~ > /dev/null
          mv ~/llvm-clang .
          
      - name: Testing
        run: |
          cd ./project/scripts
          python3 test.py
