name: Build C2EO

on:
  pull_request:
    branches:
      - master

  schedule:
    - cron:  '0 23 * * *'

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: llvm-clang.tar.gz
          key: ${{ runner.os }}-llvm-clang

      - name: Unpack LLVM
        run: |
          sudo chmod ugo+rwx llvm-clang.tar.gz
          tar -xvf llvm-clang.tar.gz -C ~ > /dev/null
          rm -r ./llvm-clang
          mv ~/llvm-clang .
      
      - name: Install clang-tidy
        run: sudo apt install clang-tidy
      
      - name: Clang-tidy
        run: |
          cd ./project/scripts
          python3 clang_tidy.py

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: llvm-clang.tar.gz
          key: ${{ runner.os }}-llvm-clang

      - name: Unpack LLVM
        run: |
          sudo chmod ugo+rwx llvm-clang.tar.gz
          tar -xvf llvm-clang.tar.gz -C ~ > /dev/null
          rm -r ./llvm-clang
          mv ~/llvm-clang .
          
      - name: Test c2eo
        run: |
          cd ./project/scripts
          python3 test.py
